class Apartment {
    static int flatNumber;
    static String towerName;
    static String address;
    static int carpetAreaSqFt;
    static int numberOfBalconies;
    static boolean hasmodularKitchen;
    static boolean furnished;
    static boolean hasfireSafety;
    static boolean rainwaterHarvesting;
    static boolean solarPanelsInstalled;
    static boolean wifiEnabled;
    static boolean smartLockSystem;
    static boolean laundryServiceAvailable;
    static boolean visitorParking;
    static boolean banquetHall;
    static boolean libraryAvailable;
    static int distanceFromMetro; 
	static int distanceFromBrigadegateway;
    static boolean nearSchool;
    static boolean nearHospital;
    static String ownershipType;

    public static void main(String Apartment[]) {
        System.out.println("Flat Number: " + flatNumber);
		flatNumber = 302;
		System.out.println("Flat Number: " + flatNumber);
        System.out.println("Tower Name: " + towerName);
		towerName = "Satva";
		System.out.println("Tower Name: " + towerName);
        System.out.println("Address: " + address);
		address = "Yeshawanthpur";
		System.out.println("Address: " + address);
        System.out.println("Carpet Area (sq ft): " + carpetAreaSqFt);
		carpetAreaSqFt = 950;
		System.out.println("Carpet Area (sq ft): " + carpetAreaSqFt);
        System.out.println("Number of Balconies: " + numberOfBalconies);
		numberOfBalconies = 2;
		System.out.println("Number of Balconies: " + numberOfBalconies);
        System.out.println("Has Modular Kitchen: " + hasmodularKitchen);
		hasmodularKitchen = true;
		System.out.println("Has Modular Kitchen: " + hasmodularKitchen);
        System.out.println("Is Furnished: " + furnished);
		furnished = false;
		System.out.println("Is Furnished: " + furnished);
        System.out.println("Fire Safety Available: " + hasfireSafety);
		hasfireSafety = true;
		System.out.println("Fire Safety Available: " + hasfireSafety);
        System.out.println("Rainwater Harvesting: " + rainwaterHarvesting);
		rainwaterHarvesting = true;
		System.out.println("Rainwater Harvesting: " + rainwaterHarvesting);
        System.out.println("Solar Panels Installed: " + solarPanelsInstalled);
		solarPanelsInstalled = false;
		System.out.println("Solar Panels Installed: " + solarPanelsInstalled);
        System.out.println("Wi-Fi Enabled: " + wifiEnabled);
		wifiEnabled = true;
		System.out.println("Wi-Fi Enabled: " + wifiEnabled);
        System.out.println("Smart Lock System: " + smartLockSystem);
		smartLockSystem = false;
		System.out.println("Smart Lock System: " + smartLockSystem);
        System.out.println("Laundry Service Available: " + laundryServiceAvailable);
		laundryServiceAvailable = true;
		System.out.println("Laundry Service Available: " + laundryServiceAvailable);
        System.out.println("Visitor Parking: " + visitorParking);
		visitorParking = true;
		System.out.println("Visitor Parking: " + visitorParking);
        System.out.println("Banquet Hall: " + banquetHall);
		banquetHall = false;
		System.out.println("Banquet Hall: " + banquetHall);
        System.out.println("Library Available: " + libraryAvailable);
		libraryAvailable = true;
		System.out.println("Library Available: " + libraryAvailable);
        System.out.println("Distance from Metro: " + distanceFromMetro);
		distanceFromMetro = 1; 
		System.out.println("Distance from Metro: " + distanceFromMetro);
		System.out.println("Distance from Brigade gate way: "+distanceFromBrigadegateway);
		distanceFromBrigadegateway = 4;
		System.out.println("Distance from Brigade gate way: "+distanceFromBrigadegateway);
        System.out.println("Near School: " + nearSchool);
		nearSchool = true;
		System.out.println("Near School: " + nearSchool);
        System.out.println("Near Hospital: " + nearHospital);
		nearHospital = false;
		System.out.println("Near Hospital: " + nearHospital);
        System.out.println("Ownership Type: " + ownershipType);
		ownershipType = "Leasehold";
		System.out.println("Ownership Type: " + ownershipType);
    }
}
