class Bank {
    static int bankCode;
    static String bankFullName;
    static String ifscCode;
    static String branchName;
    static String city;
    static String branchManager;
    static int totalStaff;
    static int totalATMs;
    static String centralOffice;
    static boolean foreignOperations;
    static double loanInterest;
    static String foundedIn;
    static boolean netBankingAvailable;
    static String bicCode;
    static String operationalCurrency;
    static String supportEmail;
    static long helplineNumber;
    static String registrationId;
    static boolean mobilePayments;
    static String institutionType;

    public static void main(String Bank[]) {
		System.out.println("Bank Code: "+bankCode);
		bankCode = 202;
		System.out.println("Bank Code: "+bankCode);
        System.out.println("Bank Full Name: " + bankFullName);
		bankFullName = "Bank Of Baroda";
		System.out.println("Bank Full Name: " + bankFullName);
        System.out.println("IFSC Code: " + ifscCode);
		ifscCode = "BOBN0005678";
		System.out.println("IFSC Code: " + ifscCode);
        System.out.println("Branch Name: " + branchName);
		branchName = "Downtown Branch";
		System.out.println("Branch Name: " + branchName);
        System.out.println("Branch Manager: " + branchManager);
		branchManager = "Ms.Verma";
		System.out.println("Branch Manager: " + branchManager);
        System.out.println("City: " + city);
		city = "Davanagere";
		System.out.println("City: " + city);
        System.out.println("Total Staff: " + totalStaff);
		totalStaff = 250;
		System.out.println("Total Staff: " + totalStaff);
        System.out.println("Total ATMs: " + totalATMs);
		totalATMs = 45;
		System.out.println("Total ATMs: " + totalATMs);
        System.out.println("Central Office: " + centralOffice);
		centralOffice = "Bengaluru";
		System.out.println("Central Office: " + centralOffice);
        System.out.println("Foreign Operations: " + foreignOperations);
		foreignOperations = false;
		System.out.println("Foreign Operations: " + foreignOperations);
        System.out.println("Loan Interest Rate: " + loanInterest);
		loanInterest = 7.2;
		System.out.println("Loan Interest Rate: " + loanInterest);
        System.out.println("Founded In: " + foundedIn);
		foundedIn = "1960";
		System.out.println("Founded In: " + foundedIn);
        System.out.println("Net Banking Available: " + netBankingAvailable);
		netBankingAvailable = false;
		System.out.println("Net Banking Available: " + netBankingAvailable);
        System.out.println("BIC Code: " + bicCode);
		bicCode = "BBCOINBBXXX";
		System.out.println("BIC Code: " + bicCode);
        System.out.println("Operational Currency: " + operationalCurrency);
		operationalCurrency = "USD";
		System.out.println("Operational Currency: " + operationalCurrency);
        System.out.println("Support Email: " + supportEmail);
		supportEmail = "support@bankofbaroda.com";
		System.out.println("Support Email: " + supportEmail);
        System.out.println("Helpline Number: " + helplineNumber);
		helplineNumber = 1800654321L;
		System.out.println("Helpline Number: " + helplineNumber);
        System.out.println("Registration ID: " + registrationId);
		registrationId = "BOB9876543";
		System.out.println("Registration ID: " + registrationId);
        System.out.println("Mobile Payments Enabled: " + mobilePayments);
		mobilePayments = false;
		System.out.println("Mobile Payments Enabled: " + mobilePayments);
        System.out.println("Institution Type: " + institutionType);
		institutionType = "Private";
		System.out.println("Institution Type: " + institutionType);
    }
}