class Court {
    static int courtCode;
    static String courtType;
    static String address;
    static String contactNumber;
    static String email;
    static int establishedYear;
    static boolean lokAdalatAvailable;
    static boolean mediationCenterAvailable;
    static boolean mobileCourtAvailable;
    static int dailyCaseLimit;
    static int staffCount;
    static boolean digitalDisplayBoards;
    static boolean hasBarAssociation;
    static boolean biometricEntry;
    static boolean wheelchairAccessible;
    static boolean womenHelpDesk;
    static boolean separateEntryForAdvocates;
    static String workingHours;
    static String barCouncilAffiliation;
    static boolean hasDocumentScanningFacility;

    public static void main(String Court[]) {
        System.out.println("Court Code: " + courtCode);
		courtCode = 789;
		System.out.println("Court Code: " + courtCode);
        System.out.println("Court Type: " + courtType);
		courtType = "District Court";
		System.out.println("Court Type: " + courtType);
        System.out.println("Address: " + address);
		address = "JC road,Chitradurga";
		System.out.println("Address: " + address);
        System.out.println("Contact Number: " + contactNumber);
		contactNumber = "020-12345678";
		System.out.println("Contact Number: " + contactNumber);
        System.out.println("Email: " + email);
		email = "contact@chitradurgadistrictcourt.gov.in";
        System.out.println("Established Year: " + establishedYear);
		establishedYear = 1950;
		System.out.println("Established Year: " + establishedYear);
        System.out.println("Lok Adalat Available: " + lokAdalatAvailable);
		lokAdalatAvailable = true;
		System.out.println("Lok Adalat Available: " + lokAdalatAvailable);
        System.out.println("Mediation Center Available: " + mediationCenterAvailable);
		mediationCenterAvailable = true;
		System.out.println("Mediation Center Available: " + mediationCenterAvailable);
        System.out.println("Mobile Court Available: " + mobileCourtAvailable);
		mobileCourtAvailable = false;
		System.out.println("Mobile Court Available: " + mobileCourtAvailable);
        System.out.println("Daily Case Limit: " + dailyCaseLimit);
		dailyCaseLimit = 500;
		System.out.println("Daily Case Limit: " + dailyCaseLimit);
        System.out.println("Staff Count: " + staffCount);
		staffCount = 250;
		System.out.println("Staff Count: " + staffCount);
        System.out.println("Digital Display Boards: " + digitalDisplayBoards);
		digitalDisplayBoards = true;
		System.out.println("Digital Display Boards: " + digitalDisplayBoards);
        System.out.println("Has Bar Association: " + hasBarAssociation);
		hasBarAssociation = true;
		System.out.println("Has Bar Association: " + hasBarAssociation);
        System.out.println("Biometric Entry: " + biometricEntry);
		biometricEntry = false;
		System.out.println("Biometric Entry: " + biometricEntry);
        System.out.println("Wheelchair Accessible: " + wheelchairAccessible);
		wheelchairAccessible = true;
		System.out.println("Wheelchair Accessible: " + wheelchairAccessible);
        System.out.println("Women Help Desk: " + womenHelpDesk);
		womenHelpDesk = true;
		System.out.println("Women Help Desk: " + womenHelpDesk);
        System.out.println("Separate Entry for Advocates: " + separateEntryForAdvocates);
		separateEntryForAdvocates = true;
		System.out.println("Separate Entry for Advocates: " + separateEntryForAdvocates);
        System.out.println("Working Hours: " + workingHours);
		workingHours = "10:00 AM - 5:00 PM";
		System.out.println("Working Hours: " + workingHours);
        System.out.println("Bar Council Affiliation: " + barCouncilAffiliation);
		barCouncilAffiliation = "Bar Council of Chitradurga & Davanagere";
		System.out.println("Bar Council Affiliation: " + barCouncilAffiliation);
        System.out.println("Document Scanning Facility: " + hasDocumentScanningFacility);
		hasDocumentScanningFacility = true;
		System.out.println("Document Scanning Facility: " + hasDocumentScanningFacility);
    }
}