class Desktop {
    static int serialNumber;
    static String modelName;
    static String formFactor;
    static double cpuSpeedGHz;
    static int cacheMemoryMB;
    static boolean opticalDriveAvailable;
    static String coolingSystem;
    static String powerSupplyWatt;
    static boolean vgaPortAvailable;
    static boolean displayPortAvailable;
    static String audioOutput;
    static String keyboardType;
    static String mouseType;
    static boolean preInstalledSoftware;
    static boolean fingerprintSensor;
    static boolean kensingtonLockSlot;
    static int monitorSizeInches;
    static String screenResolution;
    static boolean dualMonitorSupport;
    static String manufactureDate;

    public static void main(String Desktop[]) {
        System.out.println("Serial Number: " + serialNumber);
		serialNumber = 845672;
		System.out.println("Serial Number: " + serialNumber);
        System.out.println("Model Name: " + modelName);
		modelName = "HP EliteDesk 800 G6";
		System.out.println("Model Name: " + modelName);
        System.out.println("Form Factor: " + formFactor);
		formFactor = "Small Form Factor";
		System.out.println("Form Factor: " + formFactor);
        System.out.println("CPU Speed (GHz): " + cpuSpeedGHz);
		cpuSpeedGHz = 3.2;
		System.out.println("CPU Speed (GHz): " + cpuSpeedGHz);
        System.out.println("Cache Memory (MB): " + cacheMemoryMB);
		cacheMemoryMB = 12;
		System.out.println("Cache Memory (MB): " + cacheMemoryMB);
        System.out.println("Optical Drive Available: " + opticalDriveAvailable);
		opticalDriveAvailable = false;
		System.out.println("Optical Drive Available: " + opticalDriveAvailable);
        System.out.println("Cooling System: " + coolingSystem);
		coolingSystem = "Air Cooled";
		System.out.println("Cooling System: " + coolingSystem);
        System.out.println("Power Supply: " + powerSupplyWatt);
		powerSupplyWatt = "350W";
		System.out.println("Power Supply: " + powerSupplyWatt);
        System.out.println("VGA Port Available: " + vgaPortAvailable);
		vgaPortAvailable = false;
		System.out.println("VGA Port Available: " + vgaPortAvailable);
        System.out.println("DisplayPort Available: " + displayPortAvailable);
		displayPortAvailable = true;
		System.out.println("DisplayPort Available: " + displayPortAvailable);
        System.out.println("Audio Output: " + audioOutput);
		audioOutput = "3.5mm Jack";
		System.out.println("Audio Output: " + audioOutput);
        System.out.println("Keyboard Type: " + keyboardType);
		keyboardType = "Mechanical";
		System.out.println("Keyboard Type: " + keyboardType);
        System.out.println("Mouse Type: " + mouseType);
		mouseType = "Optical";
		System.out.println("Mouse Type: " + mouseType);
        System.out.println("Pre-installed Software: " + preInstalledSoftware);
		preInstalledSoftware = true;
		System.out.println("Pre-installed Software: " + preInstalledSoftware);
        System.out.println("Fingerprint Sensor: " + fingerprintSensor);
		fingerprintSensor = false;
		System.out.println("Fingerprint Sensor: " + fingerprintSensor);
        System.out.println("Kensington Lock Slot: " + kensingtonLockSlot);
		kensingtonLockSlot = true;
		System.out.println("Kensington Lock Slot: " + kensingtonLockSlot);
        System.out.println("Monitor Size (inches): " + monitorSizeInches);
		monitorSizeInches = 24;
		System.out.println("Monitor Size (inches): " + monitorSizeInches);
        System.out.println("Screen Resolution: " + screenResolution);
		screenResolution = "1920x1080";
		System.out.println("Screen Resolution: " + screenResolution);
        System.out.println("Dual Monitor Support: " + dualMonitorSupport);
		dualMonitorSupport = true;
		System.out.println("Dual Monitor Support: " + dualMonitorSupport);
        System.out.println("Manufacture Date: " + manufactureDate);
		manufactureDate = "March 2024";
		System.out.println("Manufacture Date: " + manufactureDate);
    }
}
