class Switchboard {
    static int;
    static int;
    static String;
    static String;
    static String;
    static String;
    static boolean;
    static String;
    static String;
    static String;
    static boolean;
    static boolean;
    static String ;
    static String;
    static String;
    static String;
    static int;
    static boolean;
    static String;
    static String;

    public static void main(String Switchboard[]) {
        System.out.println("Panel ID: " + panelId);
		panelId = 103;
		System.out.println("Panel ID: " + panelId);
        System.out.println("Switch Count: " + switchCount);
		switchCount = 8;
		System.out.println("Switch Count: " + switchCount);
        System.out.println("Board Material: " + boardMaterial);
		boardMaterial = "Polycarbonate";
		System.out.println("Board Material: " + boardMaterial);
        System.out.println("Board Color: " + boardColor);
		boardColor = "Gray";
		System.out.println("Board Color: " + boardColor);
        System.out.println("Brand: " + brand);
		brand = "Havells";
		System.out.println("Brand: " + brand);
        System.out.println("Series: " + series);
		series = "ElitePro";
		System.out.println("Series: " + series);
        System.out.println("Smart Enabled: " + smartEnabled);
		smartEnabled = true;
		System.out.println("Smart Enabled: " + smartEnabled);
        System.out.println("Voltage Rating: " + voltageRating);
		voltageRating = "240V";
		System.out.println("Voltage Rating: " + voltageRating);
        System.out.println("Current Capacity: " + currentCapacity);
		currentCapacity = "10A";
		System.out.println("Current Capacity: " + currentCapacity);
        System.out.println("Date of Installation: " + dateOfInstallation);
		dateOfInstallation = "15-03-2022";
		System.out.println("Date of Installation: " + dateOfInstallation);
        System.out.println("Socket Included: " + socketIncluded);
		socketIncluded = false;
		System.out.println("Socket Included: " + socketIncluded);
        System.out.println("Modular Design: " + modularDesign);
		modularDesign = false;
		System.out.println("Modular Design: " + modularDesign);
        System.out.println("Assigned Room: " + assignedRoom);
		assignedRoom = "Kitchen";
		System.out.println("Assigned Room: " + assignedRoom);
        System.out.println("Fixed Position: " + fixedPosition);
		fixedPosition = "Wall B";
		System.out.println("Fixed Position: " + fixedPosition);
        System.out.println("Conductor Type: " + conductorType);
		conductorType = "Aluminum";
		System.out.println("Conductor Type: " + conductorType);
        System.out.println("Breaker Type: " + breakerType);
		breakerType = "RCCB";
		System.out.println("Breaker Type: " + breakerType);
        System.out.println("Guarantee Years: " + guaranteeYears);
		guaranteeYears = 3;
		System.out.println("Guarantee Years: " + guaranteeYears);
        System.out.println("Has Surge Guard: " + hasSurgeGuard);
		hasSurgeGuard = false;
		System.out.println("Has Surge Guard: " + hasSurgeGuard);
        System.out.println("Service Date: " + serviceDate);
		serviceDate = "10-03-2023";
		System.out.println("Service Date: " + serviceDate);
        System.out.println("Energy Efficiency: " + energyEfficiency);
		energyEfficiency = "4 Star";
		System.out.println("Energy Efficiency: " + energyEfficiency);
    }
}