class Temple {
    static int registrationNumber;
    static String templeTitle;
    static String district;
    static String region;
    static String nation;
    static String mainGod;
    static boolean isAncient;
    static int renovationYear;
    static boolean hasMeditationCenter;
    static boolean hasGarden;
    static boolean hasMuseum;
    static int numberOfPillars;
    static boolean entryFree;
    static String darshanStart;
    static String darshanEnd;
    static boolean conductsYatra;
    static boolean providesPrasadam;
    static boolean hasCCTV;
    static boolean allowsPhotography;
    static boolean offersAccommodation;
    static boolean hasLiftFacility;

    public static void main(String Temple[]) {
        System.out.println("Registration Number: " + registrationNumber);
		registrationNumber = 2205;
		System.out.println("Updated Registration Number: " + registrationNumber);
        System.out.println("Temple Title: " + templeTitle);
		templeTitle = "Kashi Vishwanath";
		System.out.println("Updated Temple Title: " + templeTitle);
        System.out.println("District: " + district);
		district = "Varanasi";
		System.out.println("Updated District: " + district);
        System.out.println("Region: " + region);
		region = "Eastern";
		System.out.println("Updated Region: " + region);
        System.out.println("Nation: " + nation);
		nation = "Bharat";
		System.out.println("Updated Nation: " + nation);
        System.out.println("Main Deity: " + mainGod);
		mainGod = "Lord Shiva";
		System.out.println("Updated Main Deity: " + mainGod);
        System.out.println("Is Ancient Temple: " + isAncient);
		isAncient = true;
		System.out.println("Updated Is Ancient Temple: " + isAncient);
        System.out.println("Last Renovation Year: " + renovationYear);
		renovationYear = 2021;
		System.out.println("Updated Last Renovation Year: " + renovationYear);
        System.out.println("Meditation Center Available: " + hasMeditationCenter);
		hasMeditationCenter = true;
		System.out.println("Updated Meditation Center Available: " + hasMeditationCenter);
        System.out.println("Has Garden: " + hasGarden);
		hasGarden = true;
		System.out.println("Updated Has Garden: " + hasGarden);
		hasMuseum = false;
		System.out.println("Has Garden: " + hasGarden);
        System.out.println("Has Museum: " + hasMuseum);
		hasMuseum = false;
		System.out.println("Updated Has Museum: " + hasMuseum);
        System.out.println("Number of Pillars: " + numberOfPillars);
		numberOfPillars = 64;
		System.out.println("Updated Number of Pillars: " + numberOfPillars);
        System.out.println("Entry is Free: " + entryFree);
		entryFree = false;
		System.out.println("Updated Entry is Free: " + entryFree);
        System.out.println("Darshan Starts At: " + darshanStart);
		darshanStart = "5:00 AM";
		System.out.println("Updated Darshan Starts At: " + darshanStart);
        System.out.println("Darshan Ends At: " + darshanEnd);
		darshanEnd = "9:00 PM";
		System.out.println("Updated Darshan Ends At: " + darshanEnd);
        System.out.println("Conducts Yatra: " + conductsYatra);
		conductsYatra = true;
		System.out.println("Updated Conducts Yatra: " + conductsYatra);
        System.out.println("Provides Prasadam: " + providesPrasadam);
		providesPrasadam = true;
		System.out.println("Updated Provides Prasadam: " + providesPrasadam);
        System.out.println("CCTV Surveillance: " + hasCCTV);
		hasCCTV = true;
		System.out.println("Updated CCTV Surveillance: " + hasCCTV);
        System.out.println("Photography Allowed: " + allowsPhotography);
		allowsPhotography = false;
		System.out.println("Updated Photography Allowed: " + allowsPhotography);
        System.out.println("Accommodation Available: " + offersAccommodation);
		offersAccommodation = true;
		System.out.println("Updated Accommodation Available: " + offersAccommodation);
        System.out.println("Lift Facility Available: " + hasLiftFacility);
		hasLiftFacility = false;
		System.out.println("UpdatedLift Facility Available: " + hasLiftFacility);

    }
}